version: "3.8"
services:
  web:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.client
      args:
        - DOCKER_ENV=development
    image: gcr.io/circling-deploy/circling-web
    networks:
      - circling-network
    ports:
      - "8080:80"

  server:
    build:
      context: .
      dockerfile: dockerfiles/Dockerfile.server
    image: gcr.io/circling-deploy/circling-server
    networks:
      - circling-network
    env_file:
      - server/.env
    ports:
      - "4567:4567"

  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: circling
      POSTGRES_PASSWORD: circling
      POSTGRES_DB: circling_db

networks:
  circling-network:
    driver: bridge