FROM node:alpine
# RUN apk add --no-cache --virtual .gyp python make g++ 
RUN sed -i 's/dl-cdn.alpinelinux.org/mirrors.aliyun.com/g' /etc/apk/repositories
RUN apk add --no-cache --virtual python make g++

ENV PORT=4567

# WORKDIR /app
# COPY package*.json /app/
# RUN npm install

WORKDIR /app/server
COPY server/package*.json /app/server/
RUN npm install

COPY src /app/src/
COPY server /app/server/

ENTRYPOINT [ "npm", "start" ]
EXPOSE $PORT