# Install necessary tools for setting up a circling web server 
# The main items are docker and pre-requisits
- hosts: circling-web
  become: yes
  vars:
    username: deployer
    docker__users: ["{{username}}"]
    production_env_file: ~/.gcr/production.env
    users:
      - username: "{{ username }}"
  remote_user: "{{ username }}"
  roles:
    - role: "nickjj.docker"
    - role: "gantsign.oh-my-zsh"
  tasks:
    - name: docker pre-req pip
      apt:
        state: latest
        name: python-pip
    - name: docker pre-req python library
      pip:
        name:
          - docker
    - name: copy over production environment
      copy:
        src: "{{ production_env_file }}"
        dest: /home/{{ username }}/.env
        owner: "{{ username }}"
        group: "{{ username }}"