- hosts: circling-web
  remote_user: deployer
  gather_facts: no
  become: yes
  vars:
    http_conf: circlingchina.conf
  tasks:
    - name: Install nginx package
      apt:
        name: nginx
        update_cache: yes
        state: latest
    - name: Sets Nginx conf file
      template:
        src: "files/nginx.conf.j2"
        dest: "/etc/nginx/sites-available/{{ http_conf }}"
      notify: Reload Nginx
    - name: Enables new site
      file:
        src: "/etc/nginx/sites-available/{{ http_conf }}"
        dest: "/etc/nginx/sites-enabled/{{ http_conf }}"
        state: link
      notify: Reload Nginx
    - name: Removes "default" site
      file:
        path: "/etc/nginx/sites-enabled/default"
        state: absent
      notify: Reload Nginx
  # Install Certbot
    - name: Add certbot repo
      apt_repository:
        repo: ppa:certbot/certbot
    - name: Install certbot
      apt:
        name: python-certbot-nginx
  # Note: execute with `sudo certbot --nginx -d api.circlingchina.org`
  handlers:
    - name: Reload Nginx
      service:
        name: nginx
        state: reloaded

  
        